const SERVICES = [
  {
    id: 'voice-ai',
    name: 'Voice AI Systems',
    shortName: 'Voice AI',
    priceRange: { low: 2500, high: 15000 },
    description: 'AI-powered phone agents that handle calls 24/7 — no hold music, no missed leads.',
    longDescription:
      'Transform your phone presence with intelligent voice AI that handles inbound and outbound calls with natural conversation. Perfect for appointment booking, lead qualification, customer service, and after-hours support.',
    features: [
      'Natural language phone agent',
      'Appointment booking & reminders',
      'Inbound & outbound call handling',
      'Lead qualification on every call',
      'Custom voice & personality',
      'CRM integration',
      'Full call transcription & analytics',
    ],
    useCases: ['Dental offices', 'Real estate agencies', 'HVAC companies', 'Medical practices', 'Law firms'],
    timeline: '4–8 weeks',
    icon: 'mic',
    tag: 'Most Popular',
  },
  {
    id: 'chatbots',
    name: 'Custom Chatbots',
    shortName: 'Chatbots',
    priceRange: { low: 1500, high: 8000 },
    description: 'Intelligent chat assistants for your website, WhatsApp, or customer service that never sleep.',
    longDescription:
      'Deploy AI chatbots that know your business inside-out. Handle FAQs, capture leads, process orders, and escalate complex issues — all without adding headcount.',
    features: [
      'Website chat widget',
      'WhatsApp & SMS integration',
      'Lead capture & qualification',
      'FAQ automation',
      'Order tracking & support',
      'Human handoff escalation',
      'Custom training on your data',
    ],
    useCases: ['E-commerce stores', 'SaaS companies', 'Restaurants', 'Service businesses'],
    timeline: '2–4 weeks',
    icon: 'message-circle',
    tag: 'Best Value',
  },
  {
    id: 'document-ai',
    name: 'AI Document Generation',
    shortName: 'Document AI',
    priceRange: { low: 1000, high: 5000 },
    description: 'Automate contracts, proposals, invoices, and reports — generated in seconds, not hours.',
    longDescription:
      'Stop spending hours on paperwork. Our document AI generates professional, legally-sound documents from simple inputs — customized for your business and ready to send.',
    features: [
      'Contract & agreement generation',
      'Proposal & quote automation',
      'Invoice creation',
      'Report writing',
      'Custom document templates',
      'E-signature integration',
      'PDF & DOCX export',
    ],
    useCases: ['Law firms', 'Accounting firms', 'Consultants', 'Real estate agencies', 'Contractors'],
    timeline: '2–3 weeks',
    icon: 'file-text',
    tag: null,
  },
  {
    id: 'custom-models',
    name: 'Custom AI Models',
    shortName: 'Custom Models',
    priceRange: { low: 5000, high: 50000 },
    description: 'Fine-tuned models and RAG pipelines trained on your data for truly bespoke intelligence.',
    longDescription:
      'Go beyond off-the-shelf AI with models fine-tuned on your business data, domain, and voice. Build intelligent search, semantic recommendations, and custom LLMs that understand your business better than any employee.',
    features: [
      'LLM fine-tuning on proprietary data',
      'RAG pipeline development',
      'Embeddings & semantic search',
      'Custom knowledge base',
      'REST API integration',
      'Model performance monitoring',
      'Ongoing maintenance & updates',
    ],
    useCases: ['Healthcare', 'Legal tech', 'Finance firms', 'Specialized SaaS'],
    timeline: '6–16 weeks',
    icon: 'cpu',
    tag: 'Enterprise',
  },
  {
    id: 'generative-ai',
    name: 'Generative AI Apps',
    shortName: 'Gen AI Apps',
    priceRange: { low: 3000, high: 20000 },
    description: 'Custom AI-powered apps for image generation, content creation, and creative automation.',
    longDescription:
      'Build unique AI-powered applications — from image generation tools and content platforms to creative automation and AI-enhanced products. We bring the power of generative AI into purpose-built experiences.',
    features: [
      'AI image generation platforms',
      'Content creation automation',
      'Brand asset generation',
      'AI product photography',
      'Custom AI SaaS products',
      'Multi-model API integrations',
      'User management & billing',
    ],
    useCases: ['Marketing agencies', 'E-commerce brands', 'Creative studios', 'Media companies'],
    timeline: '6–12 weeks',
    icon: 'sparkles',
    tag: null,
  },
];

const PORTFOLIO = [
  {
    id: 'restaurant-chatbot',
    title: '24/7 Restaurant Reservation Bot',
    industry: 'Hospitality',
    service: 'Custom Chatbots',
    description:
      'A high-volume Italian restaurant needed to handle 200+ reservation requests per week without adding staff. We deployed a WhatsApp and website chatbot that books tables, handles special requests, and sends automated confirmations.',
    result: '87% of reservations now handled automatically',
    stats: ['200+ bookings/week', '87% automated', '0 missed inquiries'],
    gradient: 'from-amber-950 to-orange-950',
    accentColor: '#f59e0b',
  },
  {
    id: 'law-firm-docs',
    title: 'Law Firm Document Pipeline',
    industry: 'Legal',
    service: 'AI Document Generation',
    description:
      "A 12-attorney firm was spending 15+ hours per week drafting standard contracts, NDAs, and engagement letters. Our AI pipeline reduced this to minutes with custom legal templates trained on the firm's voice and style.",
    result: 'Drafting time cut from 15 hrs to under 2 hrs/week',
    stats: ['15 hrs saved weekly', '3-week delivery', '50+ template types'],
    gradient: 'from-blue-950 to-indigo-950',
    accentColor: '#4fa3e0',
  },
  {
    id: 'real-estate-voice',
    title: 'Real Estate Voice AI Lead Qualifier',
    industry: 'Real Estate',
    service: 'Voice AI Systems',
    description:
      'A real estate team was losing leads that called after business hours. We built a voice AI agent that answers every call, qualifies buyers and sellers, schedules showings, and fires a text alert to agents for hot leads.',
    result: '3× more qualified appointments booked monthly',
    stats: ['24/7 availability', '3× appointments', '$0 missed-lead cost'],
    gradient: 'from-emerald-950 to-teal-950',
    accentColor: '#10b981',
  },
  {
    id: 'ecommerce-descriptions',
    title: 'E-Commerce AI Description Generator',
    industry: 'Retail',
    service: 'Generative AI Apps',
    description:
      'A 10,000-SKU retailer needed unique, SEO-optimized product descriptions for their entire catalog. We built a generative AI app that creates compelling copy from product data, dramatically improving organic search visibility.',
    result: '10,000 descriptions generated in 48 hours',
    stats: ['10k SKUs processed', '48 hr turnaround', '+34% organic traffic'],
    gradient: 'from-purple-950 to-violet-950',
    accentColor: '#a855f7',
  },
];

module.exports = { SERVICES, PORTFOLIO };
